const state={markdown:'',sourceName:'',jobId:null,timer:null};
const $=s=>document.querySelector(s);
const els={date:$('#local-date'),category:$('#local-category'),topic:$('#local-topic'),file:$('#local-file'),fileName:$('#local-file-name'),preview:$('#local-md-preview'),instruction:$('#local-instruction'),save:$('#save-memory'),form:$('#local-form'),run:$('#local-run'),status:$('#ollama-status'),statusTitle:$('#ollama-title'),statusSub:$('#ollama-sub'),runs:$('#memory-runs'),rules:$('#memory-feedback'),agents:$('#local-agents'),jobLabel:$('#local-job-label'),jobPercent:$('#local-job-percent'),jobBar:$('#local-job-bar'),jobMessage:$('#local-job-message'),result:$('#local-result'),resultTitle:$('#local-result-title'),angle:$('#local-result-angle'),score:$('#local-score'),cards:$('#local-cards'),socialTitle:$('#local-social-title'),socialCaption:$('#local-social-caption'),tags:$('#local-tags'),hook:$('#local-hook'),feedback:$('#local-feedback'),toast:$('#toast')};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`요청 실패 (${r.status})`);return d}
function toast(m){els.toast.textContent=m;els.toast.hidden=false;setTimeout(()=>els.toast.hidden=true,3000)}
function today(){const d=new Date();const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
async function loadHealth(){try{const h=await api('/api/local/health');els.runs.textContent=`RUN ${h.memory.run_count}`;els.rules.textContent=`RULE ${h.memory.feedback_count}`;if(h.ollama.reachable&&h.ollama.model_installed){els.status.classList.add('good');els.statusTitle.textContent='LOCAL AI READY';els.statusSub.textContent=`${h.ollama.model} · Ollama 연결 정상`;els.run.disabled=false}else if(h.ollama.reachable){els.statusTitle.textContent='MODEL MISSING';els.statusSub.textContent=`${h.ollama.model} 모델을 ollama pull로 설치하세요.`;els.run.disabled=true}else{els.statusTitle.textContent='OLLAMA OFFLINE';els.statusSub.textContent='ollama serve 실행 상태를 확인하세요.';els.run.disabled=true}}catch(e){els.statusTitle.textContent='상태 확인 실패';els.statusSub.textContent=e.message;els.run.disabled=true}}
async function loadCategory(){try{const d=await api(`/api/local/category/${encodeURIComponent(els.category.value)}`);els.topic.value=`오늘의 ${els.category.value} 주요 경기와 핵심 뉴스`;els.agents.innerHTML=d.agents.map(a=>`<article class="agent-card ${a.working?'working':''}"><strong>${esc(a.name)}</strong><small>${esc(a.title)}</small><small>${a.working?'근무 중':'오늘 미배정'} · ${esc(a.team)}</small><span class="training-focus">${esc(a.training?.focus||'공통 검수')}</span><div class="training-rule">${esc(a.training?.core_rule||'MD 원문 범위에서 담당 역할 수행')}</div></article>`).join('')}catch(e){toast(e.message)}}
function stage(stage){const order=['research','editorial','feedback','render','complete'],idx=order.indexOf(stage);document.querySelectorAll('.pipe').forEach((p,i)=>{p.classList.toggle('done',i<idx);p.classList.toggle('active',p.dataset.stage===stage)})}
function jobUI(j){els.jobLabel.textContent=j.status==='failed'?'실패':j.status==='completed'?'완료':'제작 중';els.jobPercent.textContent=`${j.percent||0}%`;els.jobBar.style.width=`${j.percent||0}%`;els.jobMessage.textContent=j.error||j.message;stage(j.stage)}
async function poll(){if(!state.jobId)return;try{const j=await api(`/api/studio/jobs/${state.jobId}`);jobUI(j);if(['completed','failed'].includes(j.status)){clearInterval(state.timer);state.timer=null;state.jobId=null;els.run.disabled=false;if(j.status==='completed'){render(j.result);await loadHealth();toast('로컬 10페이지 제작 완료')}}}catch(e){clearInterval(state.timer);els.run.disabled=false;toast(e.message)}}
function render(p){els.result.hidden=false;els.resultTitle.textContent=p.master_headline;els.angle.textContent=p.editorial_angle;els.score.textContent=p.overall_score;els.cards.innerHTML=p.cards.map(c=>`<img src="${esc(c.image_url)}" alt="${esc(c.headline)}">`).join('');els.socialTitle.textContent=p.social.post_title;els.socialCaption.textContent=p.social.caption;els.tags.innerHTML=p.social.hashtags.map(t=>`<span>${esc(t)}</span>`).join('');els.hook.textContent=p.shortform_hook;els.feedback.innerHTML=p.feedback.map(f=>`<article class="feedback-card"><div class="feedback-top"><h4>${esc(f.agent_name)}</h4><span class="score">${f.score}</span></div><dl><dt>다음 개선</dt><dd>${esc(f.improve_next)}</dd><dt>학습 규칙</dt><dd>${esc(f.learning_rule)}</dd></dl></article>`).join('');els.result.scrollIntoView({behavior:'smooth',block:'start'})}
els.file.addEventListener('change',()=>{const f=els.file.files?.[0];if(!f)return;state.sourceName=f.name;els.fileName.textContent=`${f.name} · ${(f.size/1024).toFixed(1)}KB`;const r=new FileReader();r.onload=()=>{state.markdown=String(r.result||'');els.preview.textContent=state.markdown.slice(0,9000);toast('MD 파일을 읽었습니다.')};r.readAsText(f,'utf-8')});
els.category.addEventListener('change',loadCategory);
els.form.addEventListener('submit',async e=>{e.preventDefault();if(state.markdown.trim().length<20){toast('먼저 MD 파일을 선택하세요.');return}els.run.disabled=true;els.result.hidden=true;jobUI({status:'running',stage:'research',percent:5,message:'로컬 제작 작업을 등록합니다.'});try{const body={edition_date:els.date.value,category:els.category.value,topic:els.topic.value,markdown_text:state.markdown,source_name:state.sourceName||'uploaded.md',editorial_instruction:els.instruction.value,save_feedback_memory:els.save.checked};const j=await api('/api/local/jobs',{method:'POST',body:JSON.stringify(body)});state.jobId=j.id;jobUI(j);state.timer=setInterval(poll,1200)}catch(err){els.run.disabled=false;jobUI({status:'failed',stage:'failed',percent:100,error:err.message})}});
els.date.value=today();Promise.all([loadHealth(),loadCategory()]);