const $ = s => document.querySelector(s);
let current = null;
const labels = {review_required:'검수 필요',reviewed:'검수 기록 완료',scheduled_recorded:'예약 결과 기록',metrics_recorded:'성과 기록'};
function message(text){$('#message').textContent=text;}
async function api(url,body){const r=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'sports-card-news'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail));return d;}
async function summary(){const p=await api('/api/work/performance');$('#performance').textContent=p.groups.length?p.groups.map(g=>`${g.category} · ${g.window_hours}시간 · ${g.sample_count}건\n저장률 ${g.save_rate===null?'계산 불가':(g.save_rate*100).toFixed(2)+'%'} / 공유율 ${g.share_rate===null?'계산 불가':(g.share_rate*100).toFixed(2)+'%'}\n${g.interpretation}`).join('\n\n'):'성과 기록이 아직 없습니다.';}
async function refresh(selected=current){const d=await api('/api/work/sessions');$('#sessions').replaceChildren(new Option('제작물을 선택하세요',''),...d.items.map(x=>new Option(`${x.date} · ${x.league} · ${x.page_count}P · ${labels[x.status]} · ${x.title}`,x.session_id)));if(selected&&d.items.some(x=>x.session_id===selected)){$('#sessions').value=selected;await detail(selected);}else{current=null;$('#detail').hidden=true;}await summary();}
async function detail(id){current=id;autoState(id).catch(e=>message(e.message));if(!id){$('#detail').hidden=true;return;}const d=await api(`/api/work/sessions/${encodeURIComponent(id)}`);if(current!==id)return;$('#detail').hidden=false;$('#title').textContent=d.package.master_headline;$('#quality').textContent=[d.review_valid?'현재 원고 검수 기록 있음':'현재 원고 검수 필요',d.quality.scope,...d.quality.flags].join('\n');$('#cards').replaceChildren(...d.package.cards.map(c=>{const img=document.createElement('img');img.src=`/output/studio/${encodeURIComponent(id)}/card-${String(c.slide).padStart(2,'0')}.png`;img.alt=c.headline;return img;}));$('#bundle').href=`/api/work/sessions/${encodeURIComponent(id)}/bundle`;$('#review-form').reset();if(d.review){for(const [k,v]of Object.entries(d.review)){const el=$('#review-form').elements.namedItem(k);if(!el)continue;if(el.type==='checkbox')el.checked=!!v;else el.value=v;}}$('#receipt-form').reset();$('#metrics-form').reset();$('#receipt').textContent=d.receipt?JSON.stringify(d.receipt,null,2):'예약 결과 없음';$('#metrics').textContent=d.metrics?JSON.stringify(d.metrics,null,2):'성과 없음';if(d.receipt)$('#metrics-form').elements.post_id.value=d.receipt.post_id;}
function formAction(selector,path,convert){$(selector).addEventListener('submit',async e=>{e.preventDefault();if(!current)return;const id=current,button=e.target.querySelector('button');button.disabled=true;try{const data=convert(Object.fromEntries(new FormData(e.target)),e.target);await api(`/api/work/sessions/${encodeURIComponent(id)}/${path}`,data);await refresh(id);message('기록을 저장했습니다. 외부 앱 작업은 실행하지 않았습니다.');}catch(err){message(err.message);}finally{button.disabled=false;}});}
$('#import-file').addEventListener('change',async e=>{const f=e.target.files[0];if(f){if(f.size>2000000){message('JSON 파일은 2MB 이하로 선택하세요.');return;}$('#import-json').value=await f.text();}});
$('#import-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;message('원고를 검증하고 미리보기를 만드는 중입니다.');try{const d=await api('/api/work/import',JSON.parse($('#import-json').value));await refresh(d.session_id);message(`${d.page_count}페이지 원고 가져오기 완료. 최종 검수를 진행하세요.`);}catch(err){message(err.message);}finally{button.disabled=false;}});
formAction('#review-form','review',(data,form)=>{for(const k of ['facts_checked','duplicates_checked','visual_checked','rights_checked'])data[k]=form.elements.namedItem(k).checked;return data;});
formAction('#receipt-form','schedule-receipt',data=>({...data,scheduled_at:data.scheduled_at+':00+09:00',timezone:'Asia/Seoul'}));
formAction('#metrics-form','metrics',data=>{for(const k of ['window_hours','reach','impressions','likes','comments','saves','shares'])data[k]=Number(data[k]);data.collected_at+=':00+09:00';return data;});
$('#sessions').addEventListener('change',e=>detail(e.target.value).catch(e=>message(e.message)));
$('#refresh').addEventListener('click',()=>refresh().catch(e=>message(e.message)));
$('#copy-prompt').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#prompt').value);message('프롬프트를 복사했습니다. Work에 MD와 함께 전달하세요.');}catch{$('#prompt').select();message('프롬프트를 선택했습니다. Ctrl+C로 복사하세요.');}});
(async()=>{try{const d=await api('/api/work/import-schema');$('#prompt').value=d.prompt+'\n\n직원 역할:\n'+JSON.stringify(d.team,null,2)+'\n\n실측 성과 참고:\n'+JSON.stringify(d.performance,null,2)+'\n\nJSON Schema:\n'+JSON.stringify(d.schema,null,2);await refresh();message('준비 완료 · 원고 작성 또는 기존 제작물을 선택하세요.');}catch(e){message(e.message);}})();

let autoTimer;
function autoPayload(){const f=$('#auto-form');if(!f.reportValidity())throw Error('자동 실행 설정을 확인하세요.');const d=Object.fromEntries(new FormData(f));for(const k of ['content_checked','template_and_rights_checked','authorize_schedule'])d[k]=f.elements.namedItem(k).checked;d.scheduled_at+=':00+09:00';return d;}
async function autoState(id){clearTimeout(autoTimer);if(!id)return;const d=await api(`/api/auto/sessions/${encodeURIComponent(id)}`);if(current!==id)return;$('#auto-state').textContent=JSON.stringify(d,null,2);if(['queued','running'].includes(d.status))autoTimer=setTimeout(()=>autoState(id).catch(e=>message(e.message)),2500);}
$('#auto-check').addEventListener('click',async()=>{try{if(!current)throw Error('제작물을 선택하세요.');const d=await api(`/api/auto/sessions/${encodeURIComponent(current)}/check`,autoPayload());$('#auto-state').textContent=JSON.stringify(d,null,2);message('템플릿 필드와 Instagram 자동 게시 권한 확인 완료');}catch(e){message(e.message);}});
$('#auto-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('[type=submit]');b.disabled=true;try{if(!current)throw Error('제작물을 선택하세요.');const id=current;const d=await api(`/api/auto/sessions/${encodeURIComponent(id)}/run`,autoPayload());$('#auto-state').textContent=JSON.stringify(d,null,2);await autoState(id);message('자동 실행 상태를 확인하세요. 동일 세션은 중복 실행하지 않습니다.');}catch(e){message(e.message);}finally{b.disabled=false;}});
api('/api/auto/config').then(d=>{$('#auto-config').textContent=JSON.stringify(d,null,2);}).catch(e=>message(e.message));
